// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFI3UcxlU088w6M4HGuGwTRMt0infTO-o',
    appId: '1:509576126806:web:dd430862950d6a599976f7',
    messagingSenderId: '509576126806',
    projectId: 'mobile-lab-flutter-fireb-5c529',
    authDomain: 'mobile-lab-flutter-fireb-5c529.firebaseapp.com',
    storageBucket: 'mobile-lab-flutter-fireb-5c529.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHWR_wYkBm3LTefwKc2ci8HM0Y23D7jmE',
    appId: '1:509576126806:android:b2dc94ceb46d072c9976f7',
    messagingSenderId: '509576126806',
    projectId: 'mobile-lab-flutter-fireb-5c529',
    storageBucket: 'mobile-lab-flutter-fireb-5c529.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo3_Iw3yvA6D7h-mUyPkJD3Bs1f1GipP4',
    appId: '1:509576126806:ios:97f55b8c1c8aa12b9976f7',
    messagingSenderId: '509576126806',
    projectId: 'mobile-lab-flutter-fireb-5c529',
    storageBucket: 'mobile-lab-flutter-fireb-5c529.appspot.com',
    iosClientId: '509576126806-b62bqvbgtb90uh7vlj1443o8qslik6oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo3_Iw3yvA6D7h-mUyPkJD3Bs1f1GipP4',
    appId: '1:509576126806:ios:97f55b8c1c8aa12b9976f7',
    messagingSenderId: '509576126806',
    projectId: 'mobile-lab-flutter-fireb-5c529',
    storageBucket: 'mobile-lab-flutter-fireb-5c529.appspot.com',
    iosClientId: '509576126806-b62bqvbgtb90uh7vlj1443o8qslik6oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );
}
